name: Cypress Automation Tests
on: [push]
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
            fail-fast: false
            matrix:
             containers: [ 0, 1, 2, 3, 4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run:  npm install  
      - name: Run Tests
        run:  npx cypress run 
 

       
      
        